### PR TITLE
Image driver

### PR DESCRIPTION
**Pull request by kfox1111**
This is a prototype for a csi driver that uses a raw docker image as a volume source.

### CODE REVIEW

**Comment by pohly** [comment]
SIG-storage is trying to move each driver into its own repository, which will allow releasing them independently. I doubt that this driver (regardless of its merits) will be accepted here. Can't you just create your own repo and publish it from there?

**Comment by kfox1111** [comment]
Yeah, that is issue https://github.com/kubernetes-csi/drivers/issues/81. its been stalled for a very long time.

We need to get csi pod inline support into k8s for 1.14 and if we have some drivers in tree to test against, it would be better. last I talked to @vladimirvivien he mentioned just putting the pr against drivers for now until someone can actually finish up the splitting up of the drivers repo.

I'm a bit afraid sig-storage is holding up work because it wants to do everything perfect from the get go, rather then getting stuff contributed and then keep working on making it better. For API's, its really important to get them as right as possible from the start. For drivers themselves, its not so critical. Please, lets keep making progress on them.

**Comment by pohly** [comment]
@kfox1111 I was just describing the current situation. I don't have any strong opinions on this. I'll let @saad-ali decide where this driver should go.

**Comment by kfox1111** [comment]
yeah. not mad or anything. just stating that we've been struggling to contribute for a long time and keep getting stalled out. Just trying to figure out ways to make progress.

**Comment by kfox1111** [comment]
Oh, and this is also related to https://github.com/kubernetes-csi/drivers/issues/85

**Comment by kfox1111** [comment]
Its looking like the hostpath driver has finally been split out from drivers? Can we fork it for the image-driver? I'd be happy to rebase this top of that if someone can create it.

**Comment by saad-ali** [comment]
Let's move this in to it's own repo under kubernetes-csi.

Open an issue here https://github.com/kubernetes/org/issues

**Comment by kfox1111** [comment]
Closing in favour of https://github.com/kubernetes-csi/csi-driver-image-populator/pull/1

**Pull request closed without merging**
