### PR TITLE
Refactor drivers to CSI 0.2.0 spec

### PR DESCRIPTION
**Pull request by sbezverk**
Refactor example drivers and csi common bits to CSI 0.2.0 spec

### CODE REVIEW

**Comment by sbezverk** [comment]
@chakri-nelluri appreciate if you could review it.

**Comment by sbezverk** [comment]
@rootfs @childsb one more review please

**Comment by edisonxiang** [comment]
@sbezverk well done.
It is better to replace "getnodeid" with "nodegetid" in the following lines, thanks.
https://github.com/kubernetes-csi/drivers/blob/2f9830d81eb9f7af65cc0f7fc916d01e8ce4a892/pkg/csi-common/nodeserver-default.go#L48
https://github.com/kubernetes-csi/drivers/blob/2f9830d81eb9f7af65cc0f7fc916d01e8ce4a892/pkg/csi-common/nodeserver-default_test.go#L29
https://github.com/kubernetes-csi/drivers/blob/2f9830d81eb9f7af65cc0f7fc916d01e8ce4a892/pkg/cinder/nodeserver_test.go#L38
https://github.com/kubernetes-csi/drivers/blob/2f9830d81eb9f7af65cc0f7fc916d01e8ce4a892/pkg/cinder/nodeserver_test.go#L39
https://github.com/kubernetes-csi/drivers/blob/2f9830d81eb9f7af65cc0f7fc916d01e8ce4a892/pkg/cinder/nodeserver_test.go#L60

**Comment by sbezverk** [comment]
@edisonxiang thank you very much for your review, all changes are done.

**Comment by edisonxiang** [comment]
@sbezverk It seems that you need to rebase this pr:)

**Comment by sbezverk** [comment]
@edisonxiang rebased

**Comment by edisonxiang** [comment]
LGTM. Thanks very much. @sbezverk.

**Pull request merged**
