### PR TITLE
csi 0.2.0: update nfs CSI PV example

### PR DESCRIPTION
**Pull request by rootfs**
@sbezverk @xing-yang

### CODE REVIEW

**Comment by xing-yang** [comment]
lgtm.   Thanks @rootfs !

**Comment by sbezverk** [comment]
@rootfs @xing-yang  this driver will not pass sanity testing as it is missing certain checks required by CSI spec. I am not sure if somebody is going to take care of that, but hostpath can be used as an example.

**Comment by rootfs** [comment]
@lpabon do you know where is the image registry for drivers? are the images up to date?

**Comment by xing-yang** [comment]
We have quay.io/k8scsi/csi-attacher:v0.2.0 and quay.io/k8scsi/driver-registrar:v0.2.0.  I don't think the nfsplugin image is posted there yet.

**Comment by rootfs** [comment]
tested with commit https://github.com/xing-yang/drivers/commit/dfe7d4e4e68994eabaf9a395cf0f4efd7d32874c

```bash
# kubectl describe pod nginx 
....
Events:
  Type     Reason                  Age              From                     Message
  ----     ------                  ----             ----                     -------
  Warning  FailedScheduling        2m (x2 over 2m)  default-scheduler        pod has unbound PersistentVolumeClaims
  Normal   Scheduled               2m               default-scheduler        Successfully assigned nginx to 127.0.0.1
  Normal   SuccessfulAttachVolume  2m               attachdetach-controller  AttachVolume.Attach succeeded for volume "data-nfsplugin"
  Normal   SuccessfulMountVolume   2m               kubelet, 127.0.0.1       MountVolume.SetUp succeeded for volume "default-token-w8kmk"
  Normal   SuccessfulMountVolume   45s              kubelet, 127.0.0.1       MountVolume.SetUp succeeded for volume "data-nfsplugin"
  Normal   Pulling                 44s              kubelet, 127.0.0.1       pulling image "maersk/nginx"
  Normal   Pulled                  28s              kubelet, 127.0.0.1       Successfully pulled image "maersk/nginx"
  Normal   Created                 28s              kubelet, 127.0.0.1       Created container
  Normal   Started                 27s              kubelet, 127.0.0.1       Started container
# kubectl get pod
NAME                             READY     STATUS    RESTARTS   AGE
csi-attacher-nfsplugin-0         2/2       Running   0          3m
csi-nodeplugin-nfsplugin-x4wtw   2/2       Running   0          3m
nginx                            1/1       Running   0          2m
 
```

**Comment by rootfs** [comment]
CI failure is due to sanity test issue, not related to the PR.

**Comment by xing-yang** [comment]
@sbezverk I see there are some checks in NodeStageVolume/NodeUnstageVolume in your hostpath changes.  Is that what you are referring to?  Other than that, it seems that you have already changed everything else as part of your PR: https://github.com/kubernetes-csi/drivers/pull/56.  Thanks.

**Comment by sbezverk** [comment]
@xing-yang ok I just realized that nfs plugin does not implement CreateVolume/DeleteVolume as it does not support csi.ControllerServiceCapability_RPC_CREATE_DELETE_VOLUME capabilities. The failed sanity tests are testing Controller Service. SO we will need to add a check in csi sanity, to run those tests only if plugin has ControllerServiceCapability.

**Pull request merged**
