### PR TITLE
images: update image repositories

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**

> /kind cleanup

**What this PR does / why we need it**:

As part of the efforts described in this Issue: https://github.com/kubernetes/k8s.io/issues/1525 we are trying to move away from `gcp project gke-release`

This PR update the images to the ones that is available in the community registry

/assign @spiffxp @saad-ali

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by spiffxp — COMMENTED** [review]
/lgtm
I don't have approve rights

**Comment by spiffxp** [comment]
/assign @lpabon @saad-ali 
for the /approve

**Comment by cpanato** [comment]
gently ping @lpabon @saad-ali

**Comment by cpanato** [comment]
gently ping @edisonxiang @lpabon @saad-ali
seeking an `/approve` here :)

**Comment by pohly** [comment]
This repo is not maintained anymore and in particular these files are only of history interest. I don't know whether it can be officially archived.

**Comment by cpanato** [comment]
thanks @pohly 

@nikhita looks like this repo can be deprecated, what is the process for that?

**Comment by nikhita** [comment]
> @nikhita looks like this repo can be deprecated, what is the process for that?

You can open a new issue in the k/org repo with the `Repository Archival` template - https://github.com/kubernetes/org/issues/new/choose

**Comment by cpanato** [comment]
I will open the issue to archive this project

for now this PR can be closed as well
/close

**Pull request closed without merging**
