### PR TITLE
hostPath docker files

### PR DESCRIPTION
**Pull request by lpabon**

### CODE REVIEW

**Comment by rootfs** [comment]
this doesn't have to be hostpath specific; it helps build other drivers as well.

**Comment by chakri-nelluri** [comment]
Yes. We need to add it for other drivers too. I am looking for a complete make system, which will build images and is also tied to versioning.

**Comment by lpabon** [comment]
Ok, I suggest creating a new issue for making this generic for all and adding to the make system, and check this one in.

**Pull request merged**
