### PR TITLE
Typo fix in NFS driver README

### PR DESCRIPTION
**Pull request by mathu97**
Fixed typos on line 7 and 14.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @mathu97 isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by mathu97** [comment]
@linuxfoundation completed CNCF form.

**Comment by wongma7** [comment]
lgtm

**Pull request closed without merging**
