### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by gyliu513**
cherry-pick LICENSE to 0.1.0 branch.

/cc @haoqing0110 @lpabon

### CODE REVIEW

**Comment by haoqing0110** [comment]
@lpabon Can you help merge LICENSE back to branch 0.1.0 ?

**Comment by haoqing0110** [comment]
@lpabon Any update?

**Comment by gyliu513** [comment]
@lpabon Can this get merged?

**Comment by gyliu513** [comment]
Ping @lpabon

**Comment by lpabon** [comment]
sorry for the delay, thanks!

**Pull request merged**
