### PR TITLE
Correct error variables and do other linter corrections.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@saad-ali can you bless this PR ?

**Comment by pohly** [comment]
@humblec I think your changes are all good. But first we should ensure that we can replicate the execution of whatever tests you used to find these issues (I think @Madhu-1 is going to work on that, see https://github.com/kubernetes-csi/external-provisioner/pull/201) and then we need to get your changes moved over to the new `csi-drivers-host-path` repo.

**Pull request closed without merging**
