### PR TITLE
Update to CSI 0.3

### PR DESCRIPTION
**Pull request by wongma7**
* Add NodeGetInfo
* Add snapshot

As far as I can tell none of the drivers here needs non-default topology in NodeGetInfo or non-true ProbeResponse so nothing is changed wrt those things

### CODE REVIEW

**Comment by wongma7** [comment]
@codenrhoden okay, I've made those changes to pkg/flexadapter/examples/simplenfs-flexdriver/deploy/kubernetes/csi-nodeplugin-simplenfs-flexdriver.yaml and pkg/flexadapter/examples/simplenfs-flexdriver/deploy/kubernetes/csi-attacher-simplenfs-flexdriver.yaml

**Comment by wongma7** [comment]
@codenrhoden okay, I've made those changes to pkg/flexadapter/examples/simplenfs-flexdriver/deploy/kubernetes/csi-nodeplugin-simplenfs-flexdriver.yaml and pkg/flexadapter/examples/simplenfs-flexdriver/deploy/kubernetes/csi-attacher-simplenfs-flexdriver.yaml

**Comment by codenrhoden** [comment]
This looks good to me. I don't have LGTM privs, though.

It's weird that the CI test suddenly failed. I looked at the cause -- it's a valid complaint, but the mistake has been there since the hostpath was originally committed at 27bd7b8167608463d8f065a09529acc4582c2988, 7 months ago!

I'll get a PR to fix that one...

**Comment by codenrhoden** [comment]
Ah, I figured out why the tests started to fail. the `.travis.yml` file doesn't lock the Go version, and this is a change in 1.11beta1:

```sh
$ go vet $(go list ./... | grep -v vendor)
$ go1.11beta1 vet $(go1.11beta1 list ./... | grep -v vendor)
# github.com/kubernetes-csi/drivers/pkg/hostpath
pkg/hostpath/nodeserver.go:79: Verbose.Infof call needs 6 args but has 7 args
$ 
```

**Comment by codenrhoden** [comment]
@wongma7 can you rebase this? that will make the tests pass, and then the extra merge commits can be done away with as well. :)

**Comment by lpabon** [comment]
Hi @wongma7 , this all looks good, but we need one more change (which the check was introduced in csi-test a few days ago). See the error in Travis: https://travis-ci.org/kubernetes-csi/drivers/builds/402767374#L729

```
ValidateVolumeCapabilities [Controller Server]
/home/travis/gopath/src/github.com/kubernetes-csi/csi-test/pkg/sanity/tests.go:44
  should fail when the requested volume does not exist [It]
  /home/travis/gopath/src/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go:651
```

**Comment by wongma7** [comment]
OK, fixed the test in commit #2

**Pull request merged**
